server:
  port: 9998

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product-db?createDatabaseIfNotExist=true
    username: root
    password: 0003pray
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jt-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages : com.rest.api.app.dto